version: "3.8"
services:
  honey_bot:
    image: vuna2004/honeybot
    container_name: honey_bot
    volumes:
      - ./accounts:/bot/accounts
    environment:
      - HOUR_MIN=08:30
    restart: unless-stopped
volumes:
  accounts:
